#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"

 
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	~/.local/bin/eww --config "$CFG" open dashboard
 else
 	~/.local/bin/eww --config "$CFG" close dashboard
 	rm "$FILE"
 fi
